-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.28-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.7.0.6850
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping data for table fpmbd.riwayatdisiplin: ~375 rows (approximately)
INSERT INTO `riwayatdisiplin` (`IDRiwayat`, `TanggalKejadian`, `DeskripsiPelanggaran`, `Tindakan`, `Narapidana_IDNarapidana`) VALUES
	(1, '1987-11-10 21:09:42', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 96),
	(2, '1980-10-23 15:20:48', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 94),
	(3, '1971-01-29 20:09:07', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 5),
	(4, '2009-04-13 18:27:05', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Narapidana kehilangan akses ke program atau layanan tertentu', 45),
	(5, '2008-06-08 09:49:48', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 75),
	(6, '2003-04-28 11:34:55', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana kehilangan akses ke program atau layanan tertentu', 1),
	(7, '1997-04-15 23:43:43', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 91),
	(8, '1989-07-15 03:06:06', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 92),
	(9, '2003-12-22 11:19:34', 'Narapidana menyeludupkan barang terlarang', 'Narapidana dikurung di sel khusus sebagai hukuman', 65),
	(10, '1991-04-11 18:17:16', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 72),
	(11, '2011-12-28 14:17:05', 'Narapidana menyeludupkan barang terlarang', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 76),
	(12, '2013-05-10 08:23:27', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 3),
	(13, '1986-10-24 20:17:29', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 31),
	(14, '1996-08-30 09:36:08', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana dikurung di sel khusus sebagai hukuman', 74),
	(15, '2011-12-27 23:20:42', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 8),
	(16, '2002-07-12 18:07:05', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 22),
	(17, '2008-03-06 10:49:46', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 70),
	(18, '2008-02-12 12:54:25', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 51),
	(19, '2013-08-21 08:22:09', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 28),
	(20, '1995-11-12 08:35:21', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 80),
	(21, '1982-04-30 02:28:03', 'Narapidana melarikan diri dari penjara atau mencoba melarikan diri', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 59),
	(22, '1999-05-29 15:13:25', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 90),
	(23, '1989-08-17 22:51:23', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 32),
	(24, '1996-01-27 12:56:15', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 90),
	(25, '2004-06-15 08:32:14', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 85),
	(26, '2009-07-29 18:19:48', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 55),
	(27, '2008-09-03 02:26:04', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Narapidana kehilangan akses ke program atau layanan tertentu', 3),
	(28, '2011-02-24 12:19:30', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 79),
	(29, '1990-05-28 02:03:02', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 7),
	(30, '2006-06-02 07:02:11', 'Narapidana melarikan diri dari penjara atau mencoba melarikan diri', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 95),
	(31, '2005-10-08 07:15:06', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 52),
	(32, '2016-11-20 17:56:32', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Narapidana dikurung di sel khusus sebagai hukuman', 28),
	(33, '1995-03-01 03:37:57', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 41),
	(34, '2003-07-20 19:20:48', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 75),
	(35, '1992-03-28 19:36:13', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 73),
	(36, '2005-02-21 17:48:40', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 100),
	(37, '2008-04-10 01:17:20', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 37),
	(38, '2000-03-17 21:25:15', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 64),
	(39, '2008-04-05 14:06:48', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 23),
	(40, '2002-09-17 03:55:45', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 65),
	(41, '2016-08-01 00:21:46', 'Narapidana mengganggu atau mengintimidasi narapidana lain untuk mendapatkan keuntungan atau kekuasaan', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 48),
	(42, '2003-02-19 04:47:52', 'Narapidana melarikan diri dari penjara atau mencoba melarikan diri', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 99),
	(43, '1994-07-01 21:21:46', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 74),
	(44, '2024-02-02 02:36:48', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 54),
	(45, '1991-10-23 16:50:06', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 73),
	(46, '2008-06-05 11:01:19', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Narapidana dikurung di sel khusus sebagai hukuman', 81),
	(47, '2016-11-07 05:14:20', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 16),
	(48, '1995-06-04 19:15:42', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 80),
	(49, '2012-01-02 02:07:26', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 45),
	(50, '1990-05-13 17:34:06', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Narapidana dikurung di sel khusus sebagai hukuman', 92),
	(51, '2001-07-17 02:30:52', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 84),
	(52, '2010-05-02 05:07:53', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 9),
	(53, '1992-02-28 15:18:33', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 7),
	(54, '2021-11-05 11:06:07', 'Narapidana mengganggu atau mengintimidasi narapidana lain untuk mendapatkan keuntungan atau kekuasaan', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 33),
	(55, '2013-12-16 12:52:29', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Narapidana kehilangan akses ke program atau layanan tertentu', 4),
	(56, '2015-12-22 23:15:00', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 87),
	(57, '2013-06-08 13:53:40', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 55),
	(58, '1997-06-28 21:10:45', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 30),
	(59, '2006-03-12 21:50:19', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 98),
	(60, '2003-07-27 22:39:34', 'Narapidana menyeludupkan barang terlarang', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 52),
	(61, '2000-01-26 17:08:31', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 90),
	(62, '1996-11-14 22:25:39', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 42),
	(63, '1996-09-06 16:50:42', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 38),
	(64, '2011-08-07 05:02:45', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Narapidana diharuskan untuk mengikuti pelatihan tambahan', 8),
	(65, '2013-09-09 12:43:10', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 48),
	(66, '2013-10-11 08:10:05', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 28),
	(67, '2001-09-09 17:03:47', 'Narapidana mengganggu atau mengintimidasi narapidana lain untuk mendapatkan keuntungan atau kekuasaan', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 49),
	(68, '1993-05-29 14:13:29', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 93),
	(69, '2011-10-22 11:11:13', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 37),
	(70, '1988-07-02 10:06:25', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 86),
	(71, '1998-08-21 05:58:01', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Narapidana diharuskan untuk mengikuti pelatihan tambahan', 80),
	(72, '2015-01-14 11:52:20', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Narapidana kehilangan akses ke program atau layanan tertentu', 16),
	(73, '1998-03-05 13:55:22', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana kehilangan akses ke program atau layanan tertentu', 64),
	(74, '1986-09-13 08:40:45', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 18),
	(75, '1980-02-15 09:55:27', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 17),
	(76, '2003-02-11 20:42:21', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 2),
	(77, '2000-02-16 04:32:49', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 43),
	(78, '2013-09-14 02:22:47', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Narapidana dikurung di sel khusus sebagai hukuman', 3),
	(79, '1994-03-10 18:44:23', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 74),
	(80, '2010-04-10 09:58:20', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 6),
	(81, '2007-01-23 09:45:06', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 85),
	(82, '1969-09-11 00:41:51', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Narapidana diharuskan untuk mengikuti pelatihan tambahan', 63),
	(83, '2004-12-18 14:16:10', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Narapidana kehilangan akses ke program atau layanan tertentu', 62),
	(84, '1993-02-07 18:48:59', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 73),
	(85, '2010-05-19 11:58:28', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 51),
	(86, '2024-07-24 19:32:29', 'Narapidana menyeludupkan barang terlarang', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 47),
	(87, '2010-01-05 12:30:58', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 81),
	(88, '2012-06-28 16:04:18', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 37),
	(89, '2006-10-20 03:10:42', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 62),
	(90, '2014-11-23 19:58:33', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Narapidana kehilangan akses ke program atau layanan tertentu', 83),
	(91, '2004-09-19 04:00:48', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 98),
	(92, '1994-08-14 20:42:52', 'Narapidana melarikan diri dari penjara atau mencoba melarikan diri', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 93),
	(93, '2003-06-05 18:15:00', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 84),
	(94, '1987-10-07 20:22:39', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 7),
	(95, '1997-07-02 04:38:00', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 42),
	(96, '1999-06-27 02:29:01', 'Narapidana melarikan diri dari penjara atau mencoba melarikan diri', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 44),
	(97, '2005-03-25 19:26:51', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 85),
	(98, '2017-08-10 11:26:35', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 60),
	(99, '2007-04-02 20:55:43', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 65),
	(100, '1994-02-09 09:20:41', 'Narapidana memasuki area penjara yang dibatasi', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 50),
	(101, '2009-04-26 10:32:09', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana diharuskan untuk mengikuti pelatihan tambahan', 89),
	(102, '2008-05-19 10:54:34', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Narapidana kehilangan akses ke program atau layanan tertentu', 27),
	(103, '2007-05-30 21:44:42', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 6),
	(104, '1997-11-24 04:00:47', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 74),
	(105, '2007-08-04 07:11:27', 'Narapidana mengganggu atau mengintimidasi narapidana lain untuk mendapatkan keuntungan atau kekuasaan', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 76),
	(106, '2012-03-30 05:52:34', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 81),
	(107, '2019-05-11 05:30:10', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 33),
	(108, '2002-04-27 22:24:28', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 11),
	(109, '2017-11-09 16:31:15', 'Narapidana menyeludupkan barang terlarang', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 83),
	(110, '1988-01-29 08:56:13', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 72),
	(111, '2007-07-06 07:43:33', 'Narapidana menyeludupkan barang terlarang', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 75),
	(112, '1997-08-07 08:03:37', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 49),
	(113, '2010-06-28 04:51:02', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 95),
	(114, '2013-07-15 14:08:49', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 19),
	(115, '1995-09-30 12:53:04', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 57),
	(116, '1969-06-08 15:03:46', 'Narapidana melarikan diri dari penjara atau mencoba melarikan diri', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 5),
	(117, '1989-07-08 19:01:24', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 96),
	(118, '2026-01-22 05:02:35', 'Narapidana mengganggu atau mengintimidasi narapidana lain untuk mendapatkan keuntungan atau kekuasaan', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 47),
	(119, '2001-11-25 20:46:28', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana dikurung di sel khusus sebagai hukuman', 91),
	(120, '1998-09-02 15:51:02', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 93),
	(121, '1994-05-19 23:39:21', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 10),
	(122, '1990-10-03 22:37:48', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 72),
	(123, '1988-02-28 01:15:12', 'Narapidana memasuki area penjara yang dibatasi', 'Narapidana dikurung di sel khusus sebagai hukuman', 96),
	(124, '2010-10-15 14:15:41', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 9),
	(125, '2007-08-09 02:28:19', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 88),
	(126, '2002-01-01 23:20:16', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 39),
	(127, '2000-01-27 15:43:26', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 90),
	(128, '2006-09-12 19:29:16', 'Narapidana menyeludupkan barang terlarang', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 52),
	(129, '2008-07-11 22:33:07', 'Narapidana melarikan diri dari penjara atau mencoba melarikan diri', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 70),
	(130, '1992-04-14 23:34:34', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 92),
	(131, '1990-05-10 19:23:48', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 73),
	(132, '2009-12-15 11:58:34', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 95),
	(133, '2008-03-25 17:44:18', 'Narapidana mengganggu atau mengintimidasi narapidana lain untuk mendapatkan keuntungan atau kekuasaan', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 52),
	(134, '1991-08-26 21:16:11', 'Narapidana memasuki area penjara yang dibatasi', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 86),
	(135, '2005-03-09 14:05:16', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 27),
	(136, '2006-06-06 11:27:26', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 81),
	(137, '1980-06-28 10:32:13', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 66),
	(138, '2000-03-30 23:05:39', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 2),
	(139, '2003-12-11 23:01:34', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 85),
	(140, '1994-11-19 06:23:32', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 97),
	(141, '2003-09-03 04:03:03', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 70),
	(142, '1997-08-22 09:42:24', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 26),
	(143, '1979-02-28 16:39:47', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 17),
	(144, '2004-12-15 03:54:52', 'Narapidana memasuki area penjara yang dibatasi', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 22),
	(145, '2005-06-24 22:33:50', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Narapidana dikurung di sel khusus sebagai hukuman', 24),
	(146, '1978-05-24 05:46:56', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Narapidana kehilangan akses ke program atau layanan tertentu', 56),
	(147, '2004-06-13 13:42:07', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Narapidana kehilangan akses ke program atau layanan tertentu', 46),
	(148, '1986-12-14 12:15:44', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 68),
	(149, '1998-09-17 04:41:12', 'Narapidana melarikan diri dari penjara atau mencoba melarikan diri', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 93),
	(150, '1993-04-23 07:22:32', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 26),
	(151, '2008-04-14 22:07:16', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Narapidana kehilangan akses ke program atau layanan tertentu', 52),
	(152, '1994-07-21 20:33:56', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 97),
	(153, '2002-08-18 17:54:50', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 49),
	(154, '2002-03-30 10:06:12', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 64),
	(155, '2013-03-12 09:25:40', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 28),
	(156, '1991-01-25 15:05:32', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 7),
	(157, '2006-12-01 21:14:28', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Narapidana dikurung di sel khusus sebagai hukuman', 65),
	(158, '1993-09-22 00:30:49', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 73),
	(159, '2005-04-22 20:12:47', 'Narapidana menyeludupkan barang terlarang', 'Narapidana diharuskan untuk mengikuti pelatihan tambahan', 75),
	(160, '2003-12-11 06:38:29', 'Narapidana memasuki area penjara yang dibatasi', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 100),
	(161, '2014-04-13 22:49:47', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 9),
	(162, '1980-09-05 16:08:20', 'Narapidana melarikan diri dari penjara atau mencoba melarikan diri', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 17),
	(163, '1999-01-22 02:54:37', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 13),
	(164, '2005-08-29 21:21:20', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 95),
	(165, '1988-09-29 02:33:25', 'Narapidana memasuki area penjara yang dibatasi', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 86),
	(166, '1996-06-17 16:33:14', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 93),
	(167, '2000-04-21 14:29:44', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 84),
	(168, '1998-04-26 19:00:31', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 38),
	(169, '2007-06-22 04:04:15', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 100),
	(170, '2018-02-09 03:42:17', 'Narapidana memasuki area penjara yang dibatasi', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 87),
	(171, '1986-01-18 06:10:54', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 78),
	(172, '1991-11-08 10:33:38', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 86),
	(173, '1987-11-10 06:10:16', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 53),
	(174, '2010-12-03 03:38:41', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 55),
	(175, '2002-05-22 12:04:06', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 11),
	(176, '1987-07-25 18:35:04', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 32),
	(177, '2024-03-20 08:14:14', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Narapidana kehilangan akses ke program atau layanan tertentu', 54),
	(178, '2012-08-31 19:10:10', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 9),
	(179, '1989-07-22 20:34:16', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 32),
	(180, '2002-11-30 19:29:34', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 44),
	(181, '1990-04-19 21:55:23', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Narapidana diharuskan untuk mengikuti pelatihan tambahan', 92),
	(182, '2016-09-15 05:55:10', 'Narapidana melarikan diri dari penjara atau mencoba melarikan diri', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 4),
	(183, '2004-08-23 18:56:47', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Narapidana kehilangan akses ke program atau layanan tertentu', 100),
	(184, '2013-01-03 16:57:56', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 8),
	(185, '2008-06-30 23:46:28', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Narapidana dikurung di sel khusus sebagai hukuman', 98),
	(186, '1990-12-12 15:34:14', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 86),
	(187, '1990-04-18 07:45:47', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 12),
	(188, '2012-10-17 10:23:34', 'Narapidana menyeludupkan barang terlarang', 'Narapidana kehilangan akses ke program atau layanan tertentu', 88),
	(189, '2002-04-21 11:34:57', 'Narapidana menyeludupkan barang terlarang', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 43),
	(190, '2013-01-02 04:17:39', 'Narapidana mengganggu atau mengintimidasi narapidana lain untuk mendapatkan keuntungan atau kekuasaan', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 37),
	(191, '2007-08-27 01:38:33', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 95),
	(192, '1997-07-09 23:40:46', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 13),
	(193, '2014-08-04 16:43:56', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 4),
	(194, '2012-08-13 11:51:01', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 76),
	(195, '1998-08-09 06:13:26', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Narapidana dikurung di sel khusus sebagai hukuman', 30),
	(196, '2001-12-03 03:20:05', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 25),
	(197, '2003-04-08 07:15:11', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 44),
	(198, '2001-10-28 22:26:47', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 39),
	(199, '1985-03-27 16:07:41', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 36),
	(200, '2000-05-12 06:54:10', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 49),
	(201, '2014-04-19 23:06:36', 'Narapidana memasuki area penjara yang dibatasi', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 48),
	(202, '2008-07-31 03:12:16', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 98),
	(203, '2000-01-08 08:25:30', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 2),
	(204, '1994-03-12 14:28:59', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Narapidana dikurung di sel khusus sebagai hukuman', 73),
	(205, '2016-12-02 08:30:15', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 82),
	(206, '2015-12-27 06:48:41', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 16),
	(207, '1996-07-03 11:59:27', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 93),
	(208, '2010-06-24 20:08:15', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 6),
	(209, '1996-06-07 12:21:20', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 41),
	(210, '2009-08-05 08:18:39', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 89),
	(211, '2004-04-28 04:21:23', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 27),
	(212, '2007-08-23 07:32:17', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 76),
	(213, '2021-11-26 03:46:48', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 33),
	(214, '2006-08-30 16:40:51', 'Narapidana mengganggu atau mengintimidasi narapidana lain untuk mendapatkan keuntungan atau kekuasaan', 'Narapidana kehilangan akses ke program atau layanan tertentu', 81),
	(215, '2007-06-21 23:29:02', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 6),
	(216, '1993-12-02 00:31:20', 'Narapidana menyeludupkan barang terlarang', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 80),
	(217, '1996-12-26 15:53:18', 'Narapidana menyeludupkan barang terlarang', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 13),
	(218, '2017-05-20 18:29:29', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 19),
	(219, '2008-07-31 17:24:00', 'Narapidana mengganggu atau mengintimidasi narapidana lain untuk mendapatkan keuntungan atau kekuasaan', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 79),
	(220, '2001-12-29 14:45:16', 'Narapidana memasuki area penjara yang dibatasi', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 40),
	(221, '2010-05-07 00:29:18', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 23),
	(222, '2008-04-09 04:32:51', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Narapidana diharuskan untuk mengikuti pelatihan tambahan', 79),
	(223, '2001-05-19 06:47:21', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 34),
	(224, '2000-11-11 16:55:40', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 1),
	(225, '1998-09-03 04:48:18', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana dikurung di sel khusus sebagai hukuman', 74),
	(226, '2011-06-30 10:26:51', 'Narapidana menyeludupkan barang terlarang', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 15),
	(227, '2006-04-21 18:56:15', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 70),
	(228, '1996-01-17 15:01:01', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 67),
	(229, '2016-04-07 00:49:14', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana dikurung di sel khusus sebagai hukuman', 48),
	(230, '2001-06-12 13:34:34', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 84),
	(231, '2010-10-04 16:56:32', 'Narapidana memasuki area penjara yang dibatasi', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 81),
	(232, '1993-05-28 17:41:19', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 93),
	(233, '2002-12-04 21:01:46', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 39),
	(234, '2008-07-21 04:15:00', 'Narapidana melarikan diri dari penjara atau mencoba melarikan diri', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 89),
	(235, '1998-06-17 12:45:14', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana dikurung di sel khusus sebagai hukuman', 50),
	(236, '2014-01-21 03:58:00', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 28),
	(237, '2004-07-24 06:11:31', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana kehilangan akses ke program atau layanan tertentu', 34),
	(238, '2012-07-27 05:02:04', 'Narapidana memasuki area penjara yang dibatasi', 'Narapidana diharuskan untuk mengikuti pelatihan tambahan', 81),
	(239, '1998-06-29 05:56:39', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 42),
	(240, '1985-04-17 02:50:49', 'Narapidana memasuki area penjara yang dibatasi', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 18),
	(241, '1990-06-28 18:09:30', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 68),
	(242, '2003-03-04 11:06:16', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 40),
	(243, '2000-10-14 01:00:55', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Narapidana diharuskan untuk mengikuti pelatihan tambahan', 43),
	(244, '1982-07-22 18:26:28', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Narapidana kehilangan akses ke program atau layanan tertentu', 78),
	(245, '1972-07-26 01:02:59', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 63),
	(246, '2001-10-02 07:10:31', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Narapidana dikurung di sel khusus sebagai hukuman', 99),
	(247, '2013-09-11 17:34:35', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 83),
	(248, '1996-11-30 17:07:16', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 41),
	(249, '2005-06-13 16:37:44', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Narapidana dikurung di sel khusus sebagai hukuman', 22),
	(250, '2000-10-26 14:29:43', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 44),
	(251, '2008-05-04 19:34:53', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Narapidana dikurung di sel khusus sebagai hukuman', 70),
	(252, '2011-04-18 01:48:50', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 89),
	(253, '1996-02-11 02:38:42', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 50),
	(254, '2002-02-26 00:15:28', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 11),
	(255, '1987-02-09 13:09:12', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 72),
	(256, '2008-01-02 21:23:57', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 51),
	(257, '2017-04-01 04:36:09', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 19),
	(258, '2010-05-31 15:09:25', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 9),
	(259, '1969-10-20 05:08:18', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 5),
	(260, '1995-01-17 23:21:01', 'Narapidana memasuki area penjara yang dibatasi', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 58),
	(261, '2014-07-24 23:16:19', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 48),
	(262, '1971-12-25 07:42:01', 'Narapidana memasuki area penjara yang dibatasi', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 63),
	(263, '1996-02-14 22:35:25', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 67),
	(264, '2003-07-17 23:18:20', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 44),
	(265, '1988-10-08 23:35:49', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 92),
	(266, '2013-06-15 09:35:23', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Narapidana dikurung di sel khusus sebagai hukuman', 55),
	(267, '2002-02-16 09:39:27', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 40),
	(268, '2003-04-17 18:55:06', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana kehilangan akses ke program atau layanan tertentu', 99),
	(269, '2006-01-18 17:18:29', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 100),
	(270, '1995-08-05 08:01:24', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 90),
	(271, '1985-07-23 16:36:08', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 18),
	(272, '1998-08-07 15:14:18', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana kehilangan akses ke program atau layanan tertentu', 80),
	(273, '2017-01-29 13:42:43', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Narapidana kehilangan akses ke program atau layanan tertentu', 83),
	(274, '1997-02-08 20:55:19', 'Narapidana menyeludupkan barang terlarang', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 57),
	(275, '1979-01-15 01:12:43', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 59),
	(276, '1985-10-21 00:42:40', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 31),
	(277, '1996-07-18 16:52:17', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 93),
	(278, '2011-10-13 09:34:30', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Narapidana kehilangan akses ke program atau layanan tertentu', 45),
	(279, '2013-11-17 10:19:41', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 29),
	(280, '1968-11-01 17:24:06', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 21),
	(281, '2004-04-17 12:52:44', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 65),
	(282, '2008-01-22 17:03:41', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 24),
	(283, '1989-10-31 04:46:26', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 71),
	(284, '2015-10-05 10:40:46', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 28),
	(285, '2005-01-13 05:38:37', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 98),
	(286, '2006-01-20 21:07:02', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 35),
	(287, '2011-09-17 05:39:38', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Narapidana dikurung di sel khusus sebagai hukuman', 76),
	(288, '2018-06-15 07:07:34', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 54),
	(289, '2003-09-16 14:04:09', 'Narapidana mengganggu atau mengintimidasi narapidana lain untuk mendapatkan keuntungan atau kekuasaan', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 77),
	(290, '2019-04-26 17:49:02', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 4),
	(291, '1981-05-05 11:46:52', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Narapidana kehilangan akses ke program atau layanan tertentu', 17),
	(292, '2024-09-26 15:39:13', 'Narapidana melarikan diri dari penjara atau mencoba melarikan diri', 'Narapidana kehilangan akses ke program atau layanan tertentu', 47),
	(293, '2006-05-12 12:21:57', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 22),
	(294, '1994-11-19 06:47:52', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 67),
	(295, '1990-03-12 08:23:17', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 86),
	(296, '2017-04-26 07:22:25', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 28),
	(297, '1989-10-08 22:28:35', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 12),
	(298, '1993-06-06 20:46:41', 'Narapidana melarikan diri dari penjara atau mencoba melarikan diri', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 26),
	(299, '1991-06-19 23:03:40', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 7),
	(300, '2005-05-12 19:26:30', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Narapidana dikurung di sel khusus sebagai hukuman', 84),
	(301, '2011-12-27 09:02:59', 'Narapidana melarikan diri dari penjara atau mencoba melarikan diri', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 23),
	(302, '2006-12-21 13:25:56', 'Narapidana menyeludupkan barang terlarang', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 52),
	(303, '1971-10-29 02:17:47', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 63),
	(304, '2002-01-31 10:32:55', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 91),
	(305, '2016-12-25 03:03:39', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 82),
	(306, '2013-02-17 07:17:55', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 55),
	(307, '1973-12-18 04:17:42', 'Narapidana memasuki area penjara yang dibatasi', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 21),
	(308, '1992-07-01 21:04:28', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 57),
	(309, '1988-03-08 10:59:17', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 18),
	(310, '2006-05-21 23:29:07', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 62),
	(311, '2012-10-10 21:12:06', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana diharuskan untuk mengikuti pelatihan tambahan', 20),
	(312, '1985-08-25 05:27:53', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 31),
	(313, '2008-01-25 14:32:00', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 77),
	(314, '1973-10-06 13:12:18', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 5),
	(315, '1997-03-31 05:47:29', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 74),
	(316, '1975-08-01 17:43:56', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 66),
	(317, '2012-03-24 20:07:36', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 76),
	(318, '1986-10-29 14:22:35', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 53),
	(319, '2024-01-11 14:06:57', 'Narapidana menyeludupkan barang terlarang', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 47),
	(320, '2010-06-15 22:45:21', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 51),
	(321, '1999-03-10 02:05:26', 'Narapidana menyeludupkan barang terlarang', 'Narapidana dikurung di sel khusus sebagai hukuman', 91),
	(322, '1998-12-25 12:54:57', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 41),
	(323, '2011-06-02 20:07:53', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 61),
	(324, '2012-08-01 18:46:46', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 76),
	(325, '1985-09-30 02:38:26', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 72),
	(326, '2017-09-28 20:11:34', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 28),
	(327, '2010-10-05 15:47:24', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana tidak diizinkan menerima kunjungan dari keluarga dan teman untuk jangka waktu tertentu', 89),
	(328, '2005-04-16 04:04:24', 'Narapidana mengganggu atau mengintimidasi narapidana lain untuk mendapatkan keuntungan atau kekuasaan', 'Narapidana dikurung di sel khusus sebagai hukuman', 52),
	(329, '1987-07-04 14:39:05', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 92),
	(330, '2006-11-24 03:36:46', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 35),
	(331, '2009-12-18 02:36:13', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 37),
	(332, '1989-04-01 11:32:58', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Narapidana kehilangan akses ke program atau layanan tertentu', 53),
	(333, '2005-06-24 20:43:14', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 99),
	(334, '1975-04-21 23:21:47', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 56),
	(335, '1980-06-14 00:11:46', 'Narapidana berkelahi dengan narapidana lain atau menyerang petugas', 'Narapidana kehilangan akses ke program atau layanan tertentu', 59),
	(336, '2004-09-05 01:09:07', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 62),
	(337, '2005-05-07 07:03:51', 'Narapidana menyeludupkan barang terlarang', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 34),
	(338, '1979-12-12 13:31:31', 'Narapidana menolak bekerja atau melakukan pekerjaan dengan tidak benar', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 94),
	(339, '1995-12-17 02:09:16', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 80),
	(340, '1971-07-02 19:17:19', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana kehilangan akses ke program atau layanan tertentu', 63),
	(341, '2006-08-26 17:01:23', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana diharuskan untuk mengikuti pelatihan tambahan', 95),
	(342, '2005-08-28 14:54:57', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Narapidana dikurung di sel khusus sebagai hukuman', 65),
	(343, '1994-09-27 08:03:08', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 42),
	(344, '2006-12-27 14:41:54', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 22),
	(345, '1998-07-16 01:04:18', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana diharuskan untuk mengikuti pelatihan tambahan', 91),
	(346, '2003-02-27 00:14:33', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 44),
	(347, '2021-04-19 23:01:33', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 87),
	(348, '2008-09-03 04:33:50', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 61),
	(349, '2014-07-18 21:54:26', 'Narapidana membentuk kelompok atau perkumpulan yang dilarang di penjara', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 45),
	(350, '1997-05-03 23:28:39', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Petugas mengingatkan narapidana tentang konsekuensi dari perilaku mereka', 30),
	(351, '1999-03-09 13:34:10', 'Narapidana mengganggu atau mengintimidasi narapidana lain untuk mendapatkan keuntungan atau kekuasaan', 'Narapidana dikurung di sel khusus sebagai hukuman', 49),
	(352, '1988-12-22 00:34:55', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Narapidana dikurung di sel khusus sebagai hukuman', 53),
	(353, '1979-06-21 09:08:05', 'Narapidana terlibat dalam kegiatan perjudian tanpa izin', 'Narapidana dikurung di sel khusus sebagai hukuman', 17),
	(354, '1991-01-29 02:23:09', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Petugas memberi peringatan lisan kepada narapidana atas pelanggaran yang dilakukan', 7),
	(355, '1991-03-16 15:09:26', 'Narapidana menyerang atau melukai petugas atau narapidana lain', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 86),
	(356, '2000-08-23 01:53:24', 'Narapidana menyeludupkan barang terlarang', 'Narapidana diberi pekerjaan tambahan di luar tugas rutin mereka (seperti membersihkan area umum atau bekerja di dapur)', 84),
	(357, '1972-10-22 05:12:15', 'Narapidana didapati memiliki barang yang dilarang di dalam penjara', 'Narapidana dikurung di sel khusus sebagai hukuman', 5),
	(358, '2007-07-23 14:30:57', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 76),
	(359, '2015-01-11 20:53:09', 'Narapidana memasuki area penjara yang dibatasi', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 60),
	(360, '1976-09-09 04:57:28', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 59),
	(361, '1986-02-14 00:07:07', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 71),
	(362, '2005-11-02 02:09:26', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Narapidana kehilangan hak istimewa tertentu (seperti akses ke ruang rekreasi atau kunjungan)', 46),
	(363, '2001-07-25 21:17:50', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Petugas memberikan peringatan lisan kepada narapidana mengenai pelanggaran yang dilakukan', 62),
	(364, '2008-03-17 14:01:03', 'Narapidana membuat senjata tajam dari barang-barang yang tersedia di dalam penjara', 'Narapidana dipindahkan ke penjara dengan tingkat keamanan yang lebih tinggi', 52),
	(365, '2007-01-08 04:58:52', 'Narapidana berteriak dan melakukan tindakan yang mengganggu ketertiban umum', 'Petugas mencatat pelanggaran tersebut dan memperingatkan narapidana tentang konsekuensi yang mungkin terjadi jika pelanggaran terulang', 95),
	(366, '1975-02-20 04:30:04', 'Narapidana menyeludupkan barang terlarang', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 56),
	(367, '2014-12-11 10:45:11', 'Narapidana mencuri dari narapidana lain atau dari penjara', 'Narapidana dikurung di sel khusus sebagai hukuman', 28),
	(368, '2004-06-14 19:38:42', 'Narapidana mencoba merusak atau menonaktifkan infrastruktur penjara', 'Petugas memperingatkan narapidana tentang pelanggaran yang dilakukan', 85),
	(369, '1985-06-03 12:17:42', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 36),
	(370, '1986-10-03 23:37:07', 'Narapidana menggunakan program kunjungan untuk berkomunikasi dengan orang di luar penjara untuk melakukan aktivitas ilegal', 'Narapidana dikurung di sel khusus sebagai hukuman', 96),
	(371, '1989-12-20 21:29:57', 'Narapidana menggunakan atau memiliki narkoba di dalam penjara', 'Narapidana kehilangan akses ke program atau layanan tertentu', 68),
	(372, '1995-05-13 19:13:23', 'Narapidana menolak untuk mengikuti instruksi petugas dan bersikap tidak hormat', 'Narapidana kehilangan akses ke program atau layanan tertentu', 90),
	(373, '2023-08-07 23:51:34', 'Narapidana menggunakan bahasa tubuh atau isyarat yang dianggap mengancam atau tidak pantas', 'Narapidana mengalami penundaan dalam pembebasan bersyarat', 47),
	(374, '1990-09-11 08:49:21', 'Narapidana mengganggu atau mengintimidasi narapidana lain untuk mendapatkan keuntungan atau kekuasaan', 'Petugas mencatat pelanggaran tersebut dalam catatan resmi', 12),
	(375, '1994-02-07 16:57:50', 'Narapidana meniru petugas penjara dengan mengenakan seragam atau menggunakan nama mereka', 'Narapidana diharuskan untuk berpartisipasi dalam pekerjaan rehabilitatif', 67);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
